# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  grafnyc.org:
    site_hosts:
      - canonical: grafnyc.org
        redirects:
          - www.grafnyc.org
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:positiondev/grafnyc.git # replace with your Git repo URL
    repo_subtree_path: site
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    env:
        wp_home: https://grafnyc.org
        wp_siteurl: https://grafnyc.org
        disable_wp_cron: false
        db_host: graf-production.c0x5rp4xdyae.us-east-1.rds.amazonaws.com